version: '3.9'

services:
  app:
    image: cache-service:1.0.0
    container_name: cache-service-container
    build: .
    command: "uvicorn src.api.api:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8002:8000
    volumes: 
      - .:/app
